[[rulesets]]
group = "ğŸ¥— ç¾åˆ©åšé«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/Gemini-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸŒ³ å¾·æ„å¿—å¸å›½"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Anthropic.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ—¨ï¸ ChatGPT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/OpenAI.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ—¨ï¸ ChatGPT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/OpenAI-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "ğŸ—¨ï¸ ChatGPT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/OpenAI-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ¥— ç¾åˆ©åšé«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/AI.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ¥— ç¾åˆ©åšé«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/AI-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "ğŸ¥— ç¾åˆ©åšé«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/AI-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Direct.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/Direct-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/Direct-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ“± TikTok"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/TikTok.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ“± TikTok"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/TikTok-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ° å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Bilibili.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ° å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/Bilibili-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "ğŸ° å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/Bilibili-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Tencent.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/Tencent-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/Tencent-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ¬ Netflix"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Netflix.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ¬ Netflix"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/Netflix-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "ğŸ¬ Netflix"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/Netflix-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "â›… OneDrive"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/OneDrive.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "â›… OneDrive"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/OneDrive-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "â›… OneDrive"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/OneDrive-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ–¥ï¸ YouTube"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/YouTube.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ–¥ï¸ YouTube"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/YouTube-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "ğŸ–¥ï¸ YouTube"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/YouTube-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ“§ Google"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Google.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ“§ Google"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/Google-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "ğŸ“§ Google"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/Google-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ«’ æ—¥æœ¬é«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Japan.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ«’ æ—¥æœ¬é«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/Japan-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "ğŸ«’ æ—¥æœ¬é«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/Japan-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ¦\u200dğŸ”¥ é¦™æ¸¯ä¸“çº¿"
ruleset = "[]GEOIP,CLOUDFLARE,no-resolve"

[[rulesets]]
group = "ğŸŒ³ å¾·æ„å¿—å¸å›½"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Germany.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ³ å¾·æ„å¿—å¸å›½"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/Germany-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "ğŸ«’ æ—¥æœ¬é«˜é€Ÿ"
ruleset = "[]GEOIP,JP,no-resolve"

[[rulesets]]
group = "ğŸ¥— ç¾åˆ©åšé«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/America.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ¥— ç¾åˆ©åšé«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/America-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "ğŸ¥— ç¾åˆ©åšé«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/America-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ¥— ç¾åˆ©åšé«˜é€Ÿ"
ruleset = "[]GEOIP,US,no-resolve"

[[rulesets]]
group = "ğŸ¥— ç¾åˆ©åšé«˜é€Ÿ"
ruleset = "[]GEOIP,CA,no-resolve"

[[rulesets]]
group = "ğŸ¦\u200dğŸ”¥ é¦™æ¸¯ä¸“çº¿"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Hongkong.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ¦\u200dğŸ”¥ é¦™æ¸¯ä¸“çº¿"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/Hongkong-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "ğŸ¦\u200dğŸ”¥ é¦™æ¸¯ä¸“çº¿"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/Hongkong-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ¥ æ–°åŠ å¡é«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Singapore.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ¥ æ–°åŠ å¡é«˜é€Ÿ"
ruleset = "[]GEOIP,SG,no-resolve"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/ChinaMedia.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/ChinaMedia-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/ChinaMedia-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸªŸ Microsoft"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Microsoft.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸªŸ Microsoft"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/Microsoft-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸŒ å›½é™…æµåª’ä½“"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Media.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ å›½é™…æµåª’ä½“"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/Media-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "ğŸŒ å›½é™…æµåª’ä½“"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/Media-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ¦\u200dğŸ”¥ é¦™æ¸¯ä¸“çº¿"
ruleset = "[]GEOIP,HK"

[[rulesets]]
group = "ğŸ¦\u200dğŸ”¥ é¦™æ¸¯ä¸“çº¿"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Proxy.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ¦\u200dğŸ”¥ é¦™æ¸¯ä¸“çº¿"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/Proxy-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "ğŸ¦\u200dğŸ”¥ é¦™æ¸¯ä¸“çº¿"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/Proxy-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/China.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/China-ipcidr.yaml"
type = "clash-ipcidr"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/China-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸ³ æ¼ç½‘ã®é±¼"
ruleset = "[]MATCH"