[[rulesets]]
group = "â“‚ï¸ Meta"
ruleset = "[]GEOIP,FACEBOOK,no-resolve"

[[rulesets]]
group = "ğŸ“½ï¸ Netflix"
ruleset = "[]GEOIP,NETFLIX,no-resolve"

[[rulesets]]
group = "ğŸ•Šï¸ X"
ruleset = "[]GEOIP,TWITTER,no-resolve"

[[rulesets]]
group = "ğŸ’» Google"
ruleset = "[]GEOIP,GOOGLE,no-resolve"

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]GEOIP,CLOUDFLARE,no-resolve"

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]GEOIP,TELEGRAM,no-resolve"

[[rulesets]]
group = "ğŸŒˆ é¦™æ¸¯é«˜é€Ÿ"
ruleset = "[]GEOIP,HK,no-resolve"

[[rulesets]]
group = "ğŸ—½ ç¾å›½åˆ†æµ"
ruleset = "[]GEOIP,US,no-resolve"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸ³ æ¼ç½‘ã®é±¼"
ruleset = "[]MATCH"