[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Direct.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ‡ æ•°æ®é‡‡é›†"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Data.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-game-accelerator-cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ—½ ç¾å›½åˆ†æµ"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ—¨ï¸ ChatGPT"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/OpenAI.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ—¨ï¸ ChatGPT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ—¨ï¸ ChatGPT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ“± TikTok"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ§ Tencent"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ§ Tencent"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TencentVideo/TencentVideo_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ§ Tencent"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tencent-games.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ§ Tencent"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tencent.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ§ Tencent"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Tencent/Tencent_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/biliintl.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ“± æŠ–éŸ³é›†å›¢"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouYin/DouYin_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ“± æŠ–éŸ³é›†å›¢"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bytedance.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "â“‚ï¸ Meta"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/facebook.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "â“‚ï¸ Meta"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ“½ï¸ Netflix"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ•Šï¸ xAI"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/x.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ Apple"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ® Steam"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Teams/Teams_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ“š Ms.Copilot"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bing.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ“š Ms.Copilot"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Ms.Copilot.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "â›… OneDrive"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "â›… OneDrive"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/OneDrive.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/azure.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ“Ÿ Xbox"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/xbox.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ‘¬ğŸ» GitHub"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ’¾ Microsoft"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gog.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ—½ ç¾å›½åˆ†æµ"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/blizzard.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ—½ ç¾å›½åˆ†æµ"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ubisoft.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ—½ ç¾å›½åˆ†æµ"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ea.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ—½ ç¾å›½åˆ†æµ"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ› YouTube"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ’» Google"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ’¸ PayPal"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "â›º Adobe"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/adobe.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AmazonCN/AmazonCN_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/amazon.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Amazon/Amazon_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cloudflare-cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cloudflare.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloudflare/Cloudflare_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "â™¾ï¸ æ— é™æµé‡"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tracker.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "â™¾ï¸ æ— é™æµé‡"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-public-tracker.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ™ æ—¥æœ¬é«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/niconico.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ™ æ—¥æœ¬é«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/dmm.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-dev-cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-dev.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒˆ é¦™æ¸¯é«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Hongkong.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ™ æ—¥æœ¬é«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Japan.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ¸ å°æ¹¾åˆ†æµ"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Taiwan.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ¦ æ–°åŠ å¡åˆ†æµ"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Singapore.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ—½ ç¾å›½åˆ†æµ"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/America.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ—½ ç¾å›½åˆ†æµ"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Los_Angeles.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Proxy.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/xiaohongshu.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/alibaba.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Alibaba/Alibaba_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/sina.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/baidu.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/jd.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/hupu.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Youku/Youku_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/iQIYI/iQIYI_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XiaoMi/XiaoMi_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-scholar-cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-scholar-!cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cnbeta.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-media-cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-social-media-cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸ—½ ç¾å›½åˆ†æµ"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-media.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸŒ å›½å¤–æµåª’ä½“"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-porn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ å›½å¤–æµåª’ä½“"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Domain.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ å›½å¤–æµåª’ä½“"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloud/CloudCN/CloudCN_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "â˜ï¸ å›½é™…Cloud"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloud/CloudGlobal/CloudGlobal_Classical_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/China.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "â“‚ï¸ Meta"
ruleset = "[]GEOIP,FACEBOOK,no-resolve"

[[rulesets]]
group = "ğŸ“½ï¸ Netflix"
ruleset = "[]GEOIP,NETFLIX,no-resolve"

[[rulesets]]
group = "ğŸ•Šï¸ xAI"
ruleset = "[]GEOIP,TWITTER,no-resolve"

[[rulesets]]
group = "ğŸ’» Google"
ruleset = "[]GEOIP,GOOGLE,no-resolve"

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]GEOIP,CLOUDFLARE,no-resolve"

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]GEOIP,TELEGRAM,no-resolve"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,FASTLY,no-resolve"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CLOUDFRONT,no-resolve"

[[rulesets]]
group = "ğŸŒˆ é¦™æ¸¯é«˜é€Ÿ"
ruleset = "[]GEOIP,HK,no-resolve"

[[rulesets]]
group = "ğŸ™ æ—¥æœ¬é«˜é€Ÿ"
ruleset = "[]GEOIP,JP,no-resolve"

[[rulesets]]
group = "ğŸ¸ å°æ¹¾åˆ†æµ"
ruleset = "[]GEOIP,TW,no-resolve"

[[rulesets]]
group = "ğŸ¦ æ–°åŠ å¡åˆ†æµ"
ruleset = "[]GEOIP,SG,no-resolve"

[[rulesets]]
group = "ğŸ—½ ç¾å›½åˆ†æµ"
ruleset = "[]GEOIP,US,no-resolve"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸ³ æ¼ç½‘ã®é±¼"
ruleset = "[]MATCH"
