[[rulesets]]
group = "ğŸ—¨ï¸ ChatGPT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/AI.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Direct.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ“± TikTok"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/TikTok.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ‡ æ•°æ®é‡‡é›†"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Balancer.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Tencent.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Bilibili.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ“± æŠ–éŸ³é›†å›¢"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Douyin.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Game.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "â“‚ï¸ Meta"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Meta.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ“½ï¸ Netflix"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Netflix.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ•Šï¸ X"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/X.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ Apple"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Apple.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ® Steam"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Steam.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "â›… OneDrive"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/OneDrive.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ“Ÿ Xbox"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Xbox.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/GitHub.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ’¾ Microsoft"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Microsoft.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ› YouTube"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/YouTube.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ’» Google"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Google.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ’¸ PayPal"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/PayPal.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "â›º Adobe"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Adobe.yaml"
type = "clash-domain"
interval = 21600


[[rulesets]]
group = "ğŸŒˆ é¦™æ¸¯é«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Hongkong.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ™ æ—¥æœ¬é«˜é€Ÿ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Japan.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ¸ å°æ¹¾åˆ†æµ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Taiwan.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ¦ æ–°åŠ å¡åˆ†æµ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Singapore.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸ—½ ç¾å›½åˆ†æµ"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/America.yaml"
type = "clash-domain"
interval = 21600






[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Xiaohongshu.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Weibo.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/NetEaseCloudMusic.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Alibaba.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Baidu.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/JD.yaml"
type = "clash-domain"
interval = 21600




[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/Alibaba-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "â˜ï¸ å›½é™…Cloud"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/CloudGlobal.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ å›½å¤–æµåª’ä½“"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Media.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/Proxy.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-domain/China.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-classic/China-classic.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "[]RULE-SET,https://raw.githubusercontent.com/angwz/DomainRouter/release/clash-ipcidr/China-ipcidr.yaml,no-resolve"
type = "clash-ipcidr"
interval = 21600


[[rulesets]]
group = "â“‚ï¸ Meta"
ruleset = "[]GEOIP,FACEBOOK,no-resolve"

[[rulesets]]
group = "ğŸ“½ï¸ Netflix"
ruleset = "[]GEOIP,NETFLIX,no-resolve"

[[rulesets]]
group = "ğŸ•Šï¸ X"
ruleset = "[]GEOIP,TWITTER,no-resolve"

[[rulesets]]
group = "ğŸ’» Google"
ruleset = "[]GEOIP,GOOGLE,no-resolve"

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]GEOIP,CLOUDFLARE,no-resolve"

[[rulesets]]
group = "ğŸŒ  èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]GEOIP,TELEGRAM,no-resolve"

[[rulesets]]
group = "ğŸŒˆ é¦™æ¸¯é«˜é€Ÿ"
ruleset = "[]GEOIP,HK,no-resolve"

[[rulesets]]
group = "ğŸ—½ ç¾å›½åˆ†æµ"
ruleset = "[]GEOIP,US,no-resolve"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸ³ æ¼ç½‘ã®é±¼"
ruleset = "[]MATCH"
